name: Hello World!

on:
  workflow_dispatch:

jobs:
  app-setup:
    runs-on: windows-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: configure node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "pnpm"

      - name: install dependencies
        run: pnpm ci

      - name: Greeting
        run: echo "Brawo! Dobra robota" >> $GITHUB_SETUP_SUMMARY
