# workflow to caly plik
name: Hello World!

on: # trigger ktory decyduje, ze tak workflow sie uruchamia
  workflow_dispatch: # ten scenariusz uruchamiany na żądanie

jobs: # job
  app-setup: # nazwa joba
    runs-on: windows-latest # runner

    steps: # zestaw krokow
      - name: checkout repository # pobierany nasze repozytorium na maszyne wirtualna
        uses: actions/checkout@v4 # gotowa akcja

      - name: install pnpm # instalacja pnpm na maszynie wirtualnej
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: configure node # konfiguruje nasz runtime, w tym wypadku jest to node
        uses: actions/setup-node@v4 # gotowa akcja
        with: # przekazany argument
          node-version: "20.x"

      - name: install dependencies
        run: pnpm install # nasza akcja

      - name: Greeting
        run: echo "Brawo! Znakomita robota!" >> $GITHUB_STEP_SUMMARY
